### ISSUE TITLE
As a user I can explore artworks

### ISSUE THREAD

**Issue by eemmiillyy** [hashtune/Hashtune-Marketplace-Client#1]
As a user not logged in I can explore artworks

- [x] List all trending Creators (#15)
- [x] List all trending Collectors (#15)
- [x] Filter Trending Creators and Collectors by Timespan (weeks, months, year) (#15)
- [x] List all trending auctions 
- [x] View all auctions (#14)
- [x] View all artworks (#14)
- [x] Browse all profiles (#15)

What qualifies as "trending"?
